baseURL = "https://silly-goldstine-97206e.netlify.app/"
languageCode = "en-us"
theme = "raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

# navigation
[menu]

  [[menu.header]]
  name = "Curriculum"
  URL = "#education"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[menu.footer]]
  name = "Curriculum"
  URL = "#education"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "G-DD8E3D1JCK" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Marcelin"
    text2 = "SEBLE"

  [params.favicon]
    URL = "css/favicon.ico"

  [params.footer]
      copyright = "© Margaal-2021 (Theme designed by Raditian)."
      [params.footer.margaal_logo]
        x = "img/general/logo.png"
        _2x = "img/general/logo@2x.png"
        alt = "logo"